name: Build and Run Space Shooter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Build Essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install SFML Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev

      - name: Compile Space Shooter Game
        run: g++ -c main.cpp

      - name: Link and Build Space Shooter
        run: g++ main.o -o sfml-app -lsfml-graphics -lsfml-audio -lsfml-window -lsfml-system

      - name: Run Space Shooter
        run: ./sfml-app
