name: Build and Run Space Shooter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Working Directory
        run: |
          pwd
          ls
        
      - name: Install SFML Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev
          
      - name: making random file
        run: |
          touch file123.txt
    

      - name: Build Space Shooter Game
        run: |
          ls
          g++ -c main.cpp
          g++ main.o -o sfml-app -lsfml-graphics -lsfml-audio -lsfml-window -lsfml-system
        working-directory: ${{ github.workspace }}


      - name: Run Space Shooter
        run: ./sfml-app

